#!/bin/bash
envfile=$1 ; shift
echo "$ORCH_PACKAGE_NAME environment generating into $envfile"
cat <<EOF >> $envfile
export ${ORCH_PACKAGE_NAME}_DIR=$ORCH_PACKAGE_DIR
export PATH=\$(pathadd \$${ORCH_PACKAGE_NAME}_DIR/bin \$PATH)
export MANPATH \$(pathadd \$${ORCH_PACKAGE_NAME}_DIR/man \$MANPATH)
export INFOPATH \$(pathadd \$${ORCH_PACKAGE_NAME}_DIR/info \$INFOPATH)
EOF
